### ISSUE TITLE
Store view selector

### ISSUE THREAD

**Issue by vseager** [outeredge/magento-hreflang-alternateurl-module#5]
Related to https://github.com/outeredge/magento-hreflang-alternateurl-module/pull/4

There may be instances where you don't want all stores to be used, for example if there is a trade store, POS etc.

* Swap the `local`/`local_websites` logic for a fine-grained control so that you can select specific stores across the whole installation which are used in the list of alternate URLs.
* Add an `Add alternate URL for store` config option to the store view scope.
* If alternate URL is not enabled for the current store, the alternate URL's should still be in the source for that store.

## Tasks

1. Add "Add alternate URL for store" config option (store view scope)
1. Change existing logic to loop ALL stores in ALL websites and check if "Add alternate URL for store" is "Yes"
1. Remove "Local - Website" config option

**Comment by broopdias** [comment]
https://github.com/outeredge/magento-hreflang-alternateurl-module/commit/31a8990f05d2b9465cd3cffea29265bb202f3868
